# HTTP Server
[server]
    Address = ":8199"
    ServerRoot = "public"
    ServerAgent = "gf-app"
    LogPath = "./log/server"

# Logger.
[logger]
    Path = "./log/app"
    Level = "all"
    Stdout = true

# Template.
[viewer]
    Path = "template"
    DefaultFile = "index.html"
    Delimiters = ["{{", "}}"]

#gtoken
[gToken]
    CacheMode = 1
    CacheKey = "gtoken:auth"
    Timeout = 600000
    EncryptKey = "HnoVKAMjRuSyga3a"
    AuthFailMsg = "登录超时，请重新登录"
    MultiLogin = true  #后台是否允许多端同时在线

#登录用户
[users]
    admin = 123456

# Database.
[database]
    type = "mysql"
    host = "local_server"
    port = "3306"
    user = "root"
    pass = "P@ssw0rd"
    name = "ops_server_core"
    prefix = "tbl_"
    createdAt = "create_time"
    updatedAt = "update_time"
    debug = true
    # Database logger.
    [database.logger]
        Path = "./log/sql"
        Level = "all"
        Stdout = true

[gfcli]
    [[gfcli.gen.dao]]
        type = "mysql"
        host = "local_server"
        port = "3306"
        user = "root"
        pass = "P@ssw0rd"
        name = "ops_server_core"
        removePrefix = "tbl_"
    [gfcli.build]
        name = "DockerOpsServer"
        arch = "amd64"
        system = "linux"
        mod = "none"
        cgo = 0
        pack = "config,i18n,public,template"
        version = "1.0"
        output = "./bin"
        extra = ""