// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"docker-ops-server/app/dao/internal"
)

// dictDataDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type dictDataDao struct {
	*internal.DictDataDao
}

var (
	// DictData is globally public accessible object for table tbl_dict_data operations.
	DictData = dictDataDao{
		internal.NewDictDataDao(),
	}
)

// Fill with you ideas below.
