// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"docker-ops-server/app/dao/internal"
)

// opsGroupDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type opsGroupDao struct {
	*internal.OpsGroupDao
}

var (
	// OpsGroup is globally public accessible object for table tbl_ops_group operations.
	OpsGroup = opsGroupDao{
		internal.NewOpsGroupDao(),
	}
)

// Fill with you ideas below.
