// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"docker-ops-server/app/dao/internal"
)

// opsDeployTaskServerDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type opsDeployTaskServerDao struct {
	*internal.OpsDeployTaskServerDao
}

var (
	// OpsDeployTaskServer is globally public accessible object for table tbl_ops_deploy_task_server operations.
	OpsDeployTaskServer = opsDeployTaskServerDao{
		internal.NewOpsDeployTaskServerDao(),
	}
)

// Fill with you ideas below.
