// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// OpsRepositoryDao is the manager for logic model data accessing and custom defined data operations functions management.
type OpsRepositoryDao struct {
	Table   string               // Table is the underlying table name of the DAO.
	Group   string               // Group is the database configuration group name of current DAO.
	Columns OpsRepositoryColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// OpsRepositoryColumns defines and stores column names for table tbl_ops_repository.
type OpsRepositoryColumns struct {
	Id            string // 镜像仓库ID
	Name          string // 镜像仓库名称
	Remark        string // 镜像仓库描述
	Addr          string // 镜像仓库地址
	TmpLoginCmd   string // 临时登录指令
	TmpExpireTime string // 临时指令到期时间
	Status        string // 状态(-1:删除,0:停用,1:启用)
	CreateTime    string // 创建时间
	UpdateTime    string // 更新时间
}

//  opsRepositoryColumns holds the columns for table tbl_ops_repository.
var opsRepositoryColumns = OpsRepositoryColumns{
	Id:            "id",
	Name:          "name",
	Remark:        "remark",
	Addr:          "addr",
	TmpLoginCmd:   "tmp_login_cmd",
	TmpExpireTime: "tmp_expire_time",
	Status:        "status",
	CreateTime:    "create_time",
	UpdateTime:    "update_time",
}

// NewOpsRepositoryDao creates and returns a new DAO object for table data access.
func NewOpsRepositoryDao() *OpsRepositoryDao {
	return &OpsRepositoryDao{
		Group:   "default",
		Table:   "tbl_ops_repository",
		Columns: opsRepositoryColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *OpsRepositoryDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *OpsRepositoryDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *OpsRepositoryDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
