// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// OpsGroupServersDao is the manager for logic model data accessing and custom defined data operations functions management.
type OpsGroupServersDao struct {
	Table   string                 // Table is the underlying table name of the DAO.
	Group   string                 // Group is the database configuration group name of current DAO.
	Columns OpsGroupServersColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// OpsGroupServersColumns defines and stores column names for table tbl_ops_group_servers.
type OpsGroupServersColumns struct {
	GroupId  string // 分组ID
	ServerId string // 服务器ID
}

//  opsGroupServersColumns holds the columns for table tbl_ops_group_servers.
var opsGroupServersColumns = OpsGroupServersColumns{
	GroupId:  "group_id",
	ServerId: "server_id",
}

// NewOpsGroupServersDao creates and returns a new DAO object for table data access.
func NewOpsGroupServersDao() *OpsGroupServersDao {
	return &OpsGroupServersDao{
		Group:   "default",
		Table:   "tbl_ops_group_servers",
		Columns: opsGroupServersColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *OpsGroupServersDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *OpsGroupServersDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *OpsGroupServersDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
